export interface CompetitionConfig {
  code: string;
  externalId: number;
  name: string;
  country: string;
  type: 'league' | 'cup';
  activeSeasons: number[];
}

export const SUPPORTED_COMPETITIONS: CompetitionConfig[] = [
  {
    code: 'BR_SERIE_A',
    externalId: 71,
    name: 'Brasileirão Série A',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_SERIE_B',
    externalId: 72,
    name: 'Brasileirão Série B',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'COPA_DO_BRASIL',
    externalId: 73,
    name: 'Copa do Brasil',
    country: 'Brazil',
    type: 'cup',
    activeSeasons: [2026],
  },
  {
    code: 'COPA_DO_NORDESTE',
    externalId: 612,
    name: 'Copa do Nordeste',
    country: 'Brazil',
    type: 'cup',
    activeSeasons: [2026],
  },
  {
    code: 'FIFA_WORLD_CUP',
    externalId: 1,
    name: 'Copa do Mundo FIFA',
    country: 'World',
    type: 'cup',
    activeSeasons: [2026],
  },
  {
    code: 'LIBERTADORES',
    externalId: 13,
    name: 'Copa Libertadores',
    country: 'World',
    type: 'cup',
    activeSeasons: [2026],
  },
  {
    code: 'AMISTOSOS_INT',
    externalId: 10,
    name: 'Amistosos Internacionais',
    country: 'World',
    type: 'cup',
    activeSeasons: [2026],
  },
  {
    code: 'BR_MINEIRO_1',
    externalId: 629,
    name: 'Campeonato Mineiro Módulo 1',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_MINEIRO_2',
    externalId: 619,
    name: 'Campeonato Mineiro Módulo 2',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_CARIOCA_1',
    externalId: 624,
    name: 'Campeonato Carioca Série A',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_CARIOCA_2',
    externalId: 851,
    name: 'Campeonato Carioca Série A2',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_PAULISTA_1',
    externalId: 475,
    name: 'Campeonato Paulista A1',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_PAULISTA_2',
    externalId: 476,
    name: 'Campeonato Paulista A2',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_GAUCHO_1',
    externalId: 477,
    name: 'Campeonato Gaúcho Série A',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_GAUCHO_2',
    externalId: 478,
    name: 'Campeonato Gaúcho Série A2',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_GAUCHO_1_ALT',
    externalId: 622,
    name: 'Campeonato Gaúcho (Ext 622)',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_GAUCHO_2_ALT',
    externalId: 853,
    name: 'Gaúcho Divisão de Acesso (Ext 853)',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_BAIANO_1',
    externalId: 602,
    name: 'Campeonato Baiano 1ª Divisão',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_BAIANO_2',
    externalId: 613,
    name: 'Campeonato Baiano 2ª Divisão',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_PARANAENSE_1',
    externalId: 606,
    name: 'Campeonato Paranaense 1ª Divisão',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'BR_PARANAENSE_2',
    externalId: 614,
    name: 'Campeonato Paranaense 2ª Divisão',
    country: 'Brazil',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'ENG_PREMIER_LEAGUE',
    externalId: 39,
    name: 'Premier League',
    country: 'England',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'ESP_LA_LIGA',
    externalId: 140,
    name: 'La Liga',
    country: 'Spain',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'ITA_SERIE_A',
    externalId: 135,
    name: 'Serie A',
    country: 'Italy',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'GER_BUNDESLIGA',
    externalId: 78,
    name: 'Bundesliga',
    country: 'Germany',
    type: 'league',
    activeSeasons: [2026],
  },
  {
    code: 'FRA_LIGUE_1',
    externalId: 61,
    name: 'Ligue 1',
    country: 'France',
    type: 'league',
    activeSeasons: [2026],
  },
];

export const DEFAULT_COMPETITION = {
  leagueId: 71,
  season: 2026,
};
