-- AlterTable
ALTER TABLE "Fixture" ADD COLUMN "oddsHome" DOUBLE PRECISION,
ADD COLUMN "oddsDraw" DOUBLE PRECISION,
ADD COLUMN "oddsAway" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TeamStatistic" ADD COLUMN "playedHome" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "winsHome" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "drawsHome" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lossesHome" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "playedAway" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "winsAway" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "drawsAway" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lossesAway" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "goalsForHome" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "goalsAgainstHome" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "goalsForAway" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "goalsAgainstAway" INTEGER NOT NULL DEFAULT 0;
